set nocompatible
set modelines=2
set nu

set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
syntax on
filetype plugin indent on
colorscheme slate
set shell=/bin/bash

nmap <F9> :set invpaste<CR>
nmap <F10> :set invnumber<CR>:GitGutterToggle<CR>:SyntasticToggleMode<CR>

" Window split navigation
nmap <TAB> <C-w>
nmap <TAB><TAB> <C-w>w

" no 80char check on puppet
let g:syntastic_puppet_puppetlint_args='--no-80chars-check'
