#!/bin/bash

alias d="docker"
alias dps="docker ps"
alias din="docker inspect"
alias dim="docker images"
alias drun="docker run --rm"
alias drund="docker run --rm -d"
alias dstop="docker stop"
alias drm="docker rm"
alias drmi="docker rmi"
alias dlogs="docker logs"
alias dstats="docker stats"
alias dbuild="docker build"
alias dexec="docker exec"
alias dvol="docker volume"
